baseURL = "https://kernod-group.github.io/blog/"
languageCode = "zh-hans"
defaultContentLanguage = "zh-hans"
title = "Kernod Blog"
theme = "minos"
googleAnalytics = "UA-105822028-1"
publishDir = "docs"

